name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Create Cordova project
      run: |
        cordova create counterapp
        cd counterapp
        cordova platform add android
        cordova plugin add cordova-plugin-background-mode
        cordova plugin add cordova-plugin-volume-buttons

    - name: Copy application files
      run: |
        cp -a . counterapp/www/
        ls counterapp/www/

    - name: Build the project
      run: |
